# Generated by Django 3.1.5 on 2021-01-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('measurement', models.CharField(choices=[('UNIT', 'unit'), ('TEASPOON', 'tsp'), ('TABLESPOON', 'tbsp'), ('FLUID_OUNCE', 'fl oz'), ('CUP', 'cup'), ('PINT', 'pt'), ('QUART', 'qt'), ('GALLON', 'gal'), ('MILLILITER', 'mL'), ('LITER', 'L'), ('DECILITER', 'dL'), ('POUND', 'lb'), ('OUNCE', 'oz'), ('MILLIGRAM', 'mg'), ('GRAM', 'g'), ('KILOGRAM', 'kg')], default='UNIT', max_length=11)),
                ('quantity', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
