# Generated by Django 3.1.5 on 2021-01-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210125_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='r_instructions',
        ),
    ]
